name = "PSUtil"
uuid = "c9359990-26aa-4132-a63f-2538fba6135e"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.0-dev"

[deps]
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"

[compat]
CpuId = "0.2"
Suppressor = "0.2"
julia = "1"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Suppressor", "Test"]
